### ISSUE TITLE
Avoid .ino

### ISSUE THREAD

**Issue by flx5** [barafael/raPID#2]
We should try to avoid .ino files (apart from short test cases) as those are not standard C++ compliant.

**Comment by barafael** [comment]
Sort of fixed with commit dcf946952cb537dc10256dd1cb64c8a75ff0c70f.

.ino still needed, though. But no setup() or loop()! And standard C++ everywhere.

.ino must still have same name as directory, and cpp file containing the code must have a different name, also must not be main.cpp. Arduino libraries included anywhere must appear in .ino file too.
